config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :email_templates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'email_templates#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/email_message.rb
# frozen_string_literal: true

class EmailMessage
  include ActiveModel::Model

  attr_accessor :to, :subject, :body, :fields, :custom_fields

  validates :to, :subject, :body, presence: true
  validate :validate_fields, if: :custom_fields?

  def validate_fields
    if fields.nil?
      errors.add :fields, "must have #{custom_fields.join(', ')}"
    else
      missing_fields = custom_fields - fields.stringify_keys.keys
      errors.add :fields, "must have #{missing_fields.join(', ')}" if missing_fields.any?
    end
  end

  def populated_subject
    populate(subject)
  end

  def populated_body
    populate(body)
  end

  def custom_fields?
    custom_fields.present?
  end

  private

  def populate(string)
    string.gsub('{{', '%{').gsub('}}', '}') % fields
  end

  # string = "message {{abc}}"
  # string = string.gsub("{{", "%{").gsub("}}", "}")
  # string % {abc: "red"}
end

app/models/email_template.rb
# frozen_string_literal: true

class EmailTemplate < ApplicationRecord
  validates :name, :label, :body, :subject, presence: true

  validate :validate_custom_fields_format, if: :custom_fields?

  def parsed_custom_fields
    JSON.parse custom_fields if custom_fields.present?
  end

  private

  def validate_custom_fields_format
    errors.add(:custom_fields, 'invalid format') unless valid_custom_fields?
  rescue StandardError
    errors.add(:custom_fields, 'invalid format')
  end

  def valid_custom_fields?
    parsed_fields = JSON.parse custom_fields
    parsed_fields.is_a?(Array) && parsed_fields.any? && parsed_fields.uniq.length == parsed_fields.length
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/email_templates_controller.rb
# frozen_string_literal: true

class EmailTemplatesController < ApplicationController
  before_action :set_email_template, only: %i[show edit update destroy]

  # GET /email_templates or /email_templates.json
  def index
    @email_templates = EmailTemplate.all
  end

  # GET /email_templates/1 or /email_templates/1.json
  def show; end

  # GET /email_templates/new
  def new
    @email_template = EmailTemplate.new
  end

  # GET /email_templates/1/edit
  def edit; end

  # POST /email_templates or /email_templates.json
  def create
    @email_template = EmailTemplate.new(email_template_params)

    respond_to do |format|
      if @email_template.save
        format.html do
          redirect_to email_template_url(@email_template), notice: t('messages.email_template.created_successfully')
        end
        format.json { render :show, status: :created, location: @email_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_templates/1 or /email_templates/1.json
  def update
    respond_to do |format|
      if @email_template.update(email_template_params)
        format.html do
          redirect_to email_template_url(@email_template), notice: t('messages.email_template.updated_successfully')
        end
        format.json { render :show, status: :ok, location: @email_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_templates/1 or /email_templates/1.json
  def destroy
    @email_template.destroy!

    respond_to do |format|
      format.html { redirect_to email_templates_url, notice: t('messages.email_template.deleted_successfully') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_email_template
    @email_template = EmailTemplate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def email_template_params
    params.require(:email_template).permit(:name, :label, :body, :subject, :custom_fields)
  end
end

app/views/email_templates/_email_template.html.erb
<div id="<%= dom_id email_template %>">
  <p>
    <strong>Name:</strong>
    <%= email_template.name %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= email_template.label %>
  </p>

  <p>
    <strong>Body:</strong>
    <article>
      <%= email_template.body.html_safe %>
    </article>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= email_template.subject %>
  </p>

  <p>
    <strong>Custom fields:</strong>
    <article>
      <%= email_template.custom_fields %>
    </article>
  </p>

</div>

app/views/email_templates/_form.html.erb
<%= form_with(model: email_template) do |form| %>
  <% if email_template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(email_template.errors.count, "error") %> prohibited this email_template from being saved:</h2>

      <ul>
        <% email_template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class: "tinymce", rows: 20  %>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :custom_fields, style: "display: block" %>
    <%= form.text_field :custom_fields %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <%= tinymce %>
<% end %>

app/views/email_templates/edit.html.erb
<h1>Editing email template</h1>

<%= render "form", email_template: @email_template %>

<br>

<div>
  <%= link_to "Show this email template", @email_template %> |
  <%= link_to "Back to email templates", email_templates_path %>
</div>

app/views/email_templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Email templates</h1>

<div id="email_templates">
  <% @email_templates.each do |email_template| %>
  <div id="<%= dom_id email_template %>">
    <p>
      <strong>Name:</strong>
      <%= email_template.name %>
    </p>
  
    <p>
      <strong>Label:</strong>
      <%= email_template.label %>
    </p>
  
    <p>
      <strong>Subject:</strong>
      <%= email_template.subject %>
    </p>
  </div>
  
    <p>
      <%= link_to "Show this email template", email_template %>
    </p>
  <% end %>
</div>

<%= link_to "New email template", new_email_template_path %>

app/views/email_templates/new.html.erb
<h1>New email template</h1>

<%= render "form", email_template: @email_template %>

<br>

<div>
  <%= link_to "Back to email templates", email_templates_path %>
</div>

app/views/email_templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @email_template %>

<div>
  <%= link_to "Edit this email template", edit_email_template_path(@email_template) %> |
  <%= link_to "Back to email templates", email_templates_path %>

  <%= button_to "Destroy this email template", @email_template, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emailer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= tinymce_assets %>
  </head>

  <body>
    <main class="container ">
    <%= yield %>
  </main>
  </body>
</html>